<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        \DB::table('district')->insert([
            ['id'=>1, 'province_id'=>1, 'name'=>'Quận Ba Đình'],
            ['id'=>2, 'province_id'=>1, 'name'=>'Quận Hoàn Kiếm'],
            ['id'=>3, 'province_id'=>1, 'name'=>'Quận Tây Hồ'],
            ['id'=>4, 'province_id'=>1, 'name'=>'Quận Long Biên'],
            ['id'=>5, 'province_id'=>1, 'name'=>'Quận Cầu Giấy'],
            ['id'=>6, 'province_id'=>1, 'name'=>'Quận Đống Đa'],
            ['id'=>7, 'province_id'=>1, 'name'=>'Quận Hai Bà Trưng'],
            ['id'=>8, 'province_id'=>1, 'name'=>'Quận Hoàng Mai'],
            ['id'=>9, 'province_id'=>1, 'name'=>'Quận Thanh Xuân'],
            ['id'=>10, 'province_id'=>1, 'name'=>'Huyện Sóc Sơn'],
            ['id'=>11, 'province_id'=>1, 'name'=>'Huyện Đông Anh'],
            ['id'=>12, 'province_id'=>1, 'name'=>'Huyện Gia Lâm'],
            ['id'=>13, 'province_id'=>1, 'name'=>'Quận Nam Từ Liêm'],
            ['id'=>14, 'province_id'=>1, 'name'=>'Huyện Thanh Trì'],
            ['id'=>15, 'province_id'=>1, 'name'=>'Quận Bắc Từ Liêm'],
            ['id'=>16, 'province_id'=>1, 'name'=>'Huyện Mê Linh'],
            ['id'=>17, 'province_id'=>1, 'name'=>'Quận Hà Đông'],
            ['id'=>18, 'province_id'=>1, 'name'=>'Thị xã Sơn Tây'],
            ['id'=>19, 'province_id'=>1, 'name'=>'Huyện Ba Vì'],
            ['id'=>20, 'province_id'=>1, 'name'=>'Huyện Phúc Thọ'],
            ['id'=>21, 'province_id'=>1, 'name'=>'Huyện Đan Phượng'],
            ['id'=>22, 'province_id'=>1, 'name'=>'Huyện Hoài Đức'],
            ['id'=>23, 'province_id'=>1, 'name'=>'Huyện Quốc Oai'],
            ['id'=>24, 'province_id'=>1, 'name'=>'Huyện Thạch Thất'],
            ['id'=>25, 'province_id'=>1, 'name'=>'Huyện Chương Mỹ'],
            ['id'=>26, 'province_id'=>1, 'name'=>'Huyện Thanh Oai'],
            ['id'=>27, 'province_id'=>1, 'name'=>'Huyện Thường Tín'],
            ['id'=>28, 'province_id'=>1, 'name'=>'Huyện Phú Xuyên'],
            ['id'=>29, 'province_id'=>1, 'name'=>'Huyện Ứng Hòa'],
            ['id'=>30, 'province_id'=>1, 'name'=>'Huyện Mỹ Đức'],
            ['id'=>31, 'province_id'=>2, 'name'=>'Thành phố Hà Giang'],
            ['id'=>32, 'province_id'=>2, 'name'=>'Huyện Đồng Văn'],
            ['id'=>33, 'province_id'=>2, 'name'=>'Huyện Mèo Vạc'],
            ['id'=>34, 'province_id'=>2, 'name'=>'Huyện Yên Minh'],
            ['id'=>35, 'province_id'=>2, 'name'=>'Huyện Quản Bạ'],
            ['id'=>36, 'province_id'=>2, 'name'=>'Huyện Vị Xuyên'],
            ['id'=>37, 'province_id'=>2, 'name'=>'Huyện Bắc Mê'],
            ['id'=>38, 'province_id'=>2, 'name'=>'Huyện Hoàng Su Phì'],
            ['id'=>39, 'province_id'=>2, 'name'=>'Huyện Xín Mần'],
            ['id'=>40, 'province_id'=>2, 'name'=>'Huyện Bắc Quang'],
            ['id'=>41, 'province_id'=>2, 'name'=>'Huyện Quang Bình'],
            ['id'=>42, 'province_id'=>3, 'name'=>'Thành phố Cao Bằng'],
            ['id'=>43, 'province_id'=>3, 'name'=>'Huyện Bảo Lâm'],
            ['id'=>44, 'province_id'=>3, 'name'=>'Huyện Bảo Lạc'],
            ['id'=>45, 'province_id'=>3, 'name'=>'Huyện Hà Quảng'],
            ['id'=>46, 'province_id'=>3, 'name'=>'Huyện Trùng Khánh'],
            ['id'=>47, 'province_id'=>3, 'name'=>'Huyện Hạ Lang'],
            ['id'=>48, 'province_id'=>3, 'name'=>'Huyện Quảng Hòa'],
            ['id'=>49, 'province_id'=>3, 'name'=>'Huyện Hoà An'],
            ['id'=>50, 'province_id'=>3, 'name'=>'Huyện Nguyên Bình'],
            ['id'=>51, 'province_id'=>3, 'name'=>'Huyện Thạch An'],
            ['id'=>52, 'province_id'=>4, 'name'=>'Thành Phố Bắc Kạn'],
            ['id'=>53, 'province_id'=>4, 'name'=>'Huyện Pác Nặm'],
            ['id'=>54, 'province_id'=>4, 'name'=>'Huyện Ba Bể'],
            ['id'=>55, 'province_id'=>4, 'name'=>'Huyện Ngân Sơn'],
            ['id'=>56, 'province_id'=>4, 'name'=>'Huyện Bạch Thông'],
            ['id'=>57, 'province_id'=>4, 'name'=>'Huyện Chợ Đồn'],
            ['id'=>58, 'province_id'=>4, 'name'=>'Huyện Chợ Mới'],
            ['id'=>59, 'province_id'=>4, 'name'=>'Huyện Na Rì'],
            ['id'=>60, 'province_id'=>5, 'name'=>'Thành phố Tuyên Quang'],
            ['id'=>61, 'province_id'=>5, 'name'=>'Huyện Lâm Bình'],
            ['id'=>62, 'province_id'=>5, 'name'=>'Huyện Na Hang'],
            ['id'=>63, 'province_id'=>5, 'name'=>'Huyện Chiêm Hóa'],
            ['id'=>64, 'province_id'=>5, 'name'=>'Huyện Hàm Yên'],
            ['id'=>65, 'province_id'=>5, 'name'=>'Huyện Yên Sơn'],
            ['id'=>66, 'province_id'=>5, 'name'=>'Huyện Sơn Dương'],
            ['id'=>67, 'province_id'=>6, 'name'=>'Thành phố Lào Cai'],
            ['id'=>68, 'province_id'=>6, 'name'=>'Huyện Bát Xát'],
            ['id'=>69, 'province_id'=>6, 'name'=>'Huyện Mường Khương'],
            ['id'=>70, 'province_id'=>6, 'name'=>'Huyện Si Ma Cai'],
            ['id'=>71, 'province_id'=>6, 'name'=>'Huyện Bắc Hà'],
            ['id'=>72, 'province_id'=>6, 'name'=>'Huyện Bảo Thắng'],
            ['id'=>73, 'province_id'=>6, 'name'=>'Huyện Bảo Yên'],
            ['id'=>74, 'province_id'=>6, 'name'=>'Thị xã Sa Pa'],
            ['id'=>75, 'province_id'=>6, 'name'=>'Huyện Văn Bàn'],
            ['id'=>76, 'province_id'=>7, 'name'=>'Thành phố Điện Biên Phủ'],
            ['id'=>77, 'province_id'=>7, 'name'=>'Thị Xã Mường Lay'],
            ['id'=>78, 'province_id'=>7, 'name'=>'Huyện Mường Nhé'],
            ['id'=>79, 'province_id'=>7, 'name'=>'Huyện Mường Chà'],
            ['id'=>80, 'province_id'=>7, 'name'=>'Huyện Tủa Chùa'],
            ['id'=>81, 'province_id'=>7, 'name'=>'Huyện Tuần Giáo'],
            ['id'=>82, 'province_id'=>7, 'name'=>'Huyện Điện Biên'],
            ['id'=>83, 'province_id'=>7, 'name'=>'Huyện Điện Biên Đông'],
            ['id'=>84, 'province_id'=>7, 'name'=>'Huyện Mường Ảng'],
            ['id'=>85, 'province_id'=>7, 'name'=>'Huyện Nậm Pồ'],
            ['id'=>86, 'province_id'=>8, 'name'=>'Thành phố Lai Châu'],
            ['id'=>87, 'province_id'=>8, 'name'=>'Huyện Tam Đường'],
            ['id'=>88, 'province_id'=>8, 'name'=>'Huyện Mường Tè'],
            ['id'=>89, 'province_id'=>8, 'name'=>'Huyện Sìn Hồ'],
            ['id'=>90, 'province_id'=>8, 'name'=>'Huyện Phong Thổ'],
            ['id'=>91, 'province_id'=>8, 'name'=>'Huyện Than Uyên'],
            ['id'=>92, 'province_id'=>8, 'name'=>'Huyện Tân Uyên'],
            ['id'=>93, 'province_id'=>8, 'name'=>'Huyện Nậm Nhùn'],
            ['id'=>94, 'province_id'=>9, 'name'=>'Thành phố Sơn La'],
            ['id'=>95, 'province_id'=>9, 'name'=>'Huyện Quỳnh Nhai'],
            ['id'=>96, 'province_id'=>9, 'name'=>'Huyện Thuận Châu'],
            ['id'=>97, 'province_id'=>9, 'name'=>'Huyện Mường La'],
            ['id'=>98, 'province_id'=>9, 'name'=>'Huyện Bắc Yên'],
            ['id'=>99, 'province_id'=>9, 'name'=>'Huyện Phù Yên'],
            ['id'=>100, 'province_id'=>9, 'name'=>'Huyện Mộc Châu'],
            ['id'=>101, 'province_id'=>9, 'name'=>'Huyện Yên Châu'],
            ['id'=>102, 'province_id'=>9, 'name'=>'Huyện Mai Sơn'],
            ['id'=>103, 'province_id'=>9, 'name'=>'Huyện Sông Mã'],
            ['id'=>104, 'province_id'=>9, 'name'=>'Huyện Sốp Cộp'],
            ['id'=>105, 'province_id'=>9, 'name'=>'Huyện Vân Hồ'],
            ['id'=>106, 'province_id'=>10, 'name'=>'Thành phố Yên Bái'],
            ['id'=>107, 'province_id'=>10, 'name'=>'Thị xã Nghĩa Lộ'],
            ['id'=>108, 'province_id'=>10, 'name'=>'Huyện Lục Yên'],
            ['id'=>109, 'province_id'=>10, 'name'=>'Huyện Văn Yên'],
            ['id'=>110, 'province_id'=>10, 'name'=>'Huyện Mù Căng Chải'],
            ['id'=>111, 'province_id'=>10, 'name'=>'Huyện Trấn Yên'],
            ['id'=>112, 'province_id'=>10, 'name'=>'Huyện Trạm Tấu'],
            ['id'=>113, 'province_id'=>10, 'name'=>'Huyện Văn Chấn'],
            ['id'=>114, 'province_id'=>10, 'name'=>'Huyện Yên Bình'],
            ['id'=>115, 'province_id'=>11, 'name'=>'Thành phố Hòa Bình'],
            ['id'=>116, 'province_id'=>11, 'name'=>'Huyện Đà Bắc'],
            ['id'=>117, 'province_id'=>11, 'name'=>'Huyện Lương Sơn'],
            ['id'=>118, 'province_id'=>11, 'name'=>'Huyện Kim Bôi'],
            ['id'=>119, 'province_id'=>11, 'name'=>'Huyện Cao Phong'],
            ['id'=>120, 'province_id'=>11, 'name'=>'Huyện Tân Lạc'],
            ['id'=>121, 'province_id'=>11, 'name'=>'Huyện Mai Châu'],
            ['id'=>122, 'province_id'=>11, 'name'=>'Huyện Lạc Sơn'],
            ['id'=>123, 'province_id'=>11, 'name'=>'Huyện Yên Thủy'],
            ['id'=>124, 'province_id'=>11, 'name'=>'Huyện Lạc Thủy'],
            ['id'=>125, 'province_id'=>12, 'name'=>'Thành phố Thái Nguyên'],
            ['id'=>126, 'province_id'=>12, 'name'=>'Thành phố Sông Công'],
            ['id'=>127, 'province_id'=>12, 'name'=>'Huyện Định Hóa'],
            ['id'=>128, 'province_id'=>12, 'name'=>'Huyện Phú Lương'],
            ['id'=>129, 'province_id'=>12, 'name'=>'Huyện Đồng Hỷ'],
            ['id'=>130, 'province_id'=>12, 'name'=>'Huyện Võ Nhai'],
            ['id'=>131, 'province_id'=>12, 'name'=>'Huyện Đại Từ'],
            ['id'=>132, 'province_id'=>12, 'name'=>'Thị xã Phổ Yên'],
            ['id'=>133, 'province_id'=>12, 'name'=>'Huyện Phú Bình'],
            ['id'=>134, 'province_id'=>13, 'name'=>'Thành phố Lạng Sơn'],
            ['id'=>135, 'province_id'=>13, 'name'=>'Huyện Tràng Định'],
            ['id'=>136, 'province_id'=>13, 'name'=>'Huyện Bình Gia'],
            ['id'=>137, 'province_id'=>13, 'name'=>'Huyện Văn Lãng'],
            ['id'=>138, 'province_id'=>13, 'name'=>'Huyện Cao Lộc'],
            ['id'=>139, 'province_id'=>13, 'name'=>'Huyện Văn Quan'],
            ['id'=>140, 'province_id'=>13, 'name'=>'Huyện Bắc Sơn'],
            ['id'=>141, 'province_id'=>13, 'name'=>'Huyện Hữu Lũng'],
            ['id'=>142, 'province_id'=>13, 'name'=>'Huyện Chi Lăng'],
            ['id'=>143, 'province_id'=>13, 'name'=>'Huyện Lộc Bình'],
            ['id'=>144, 'province_id'=>13, 'name'=>'Huyện Đình Lập'],
            ['id'=>145, 'province_id'=>14, 'name'=>'Thành phố Hạ Long'],
            ['id'=>146, 'province_id'=>14, 'name'=>'Thành phố Móng Cái'],
            ['id'=>147, 'province_id'=>14, 'name'=>'Thành phố Cẩm Phả'],
            ['id'=>148, 'province_id'=>14, 'name'=>'Thành phố Uông Bí'],
            ['id'=>149, 'province_id'=>14, 'name'=>'Huyện Bình Liêu'],
            ['id'=>150, 'province_id'=>14, 'name'=>'Huyện Tiên Yên'],
            ['id'=>151, 'province_id'=>14, 'name'=>'Huyện Đầm Hà'],
            ['id'=>152, 'province_id'=>14, 'name'=>'Huyện Hải Hà'],
            ['id'=>153, 'province_id'=>14, 'name'=>'Huyện Ba Chẽ'],
            ['id'=>154, 'province_id'=>14, 'name'=>'Huyện Vân Đồn'],
            ['id'=>155, 'province_id'=>14, 'name'=>'Thị xã Đông Triều'],
            ['id'=>156, 'province_id'=>14, 'name'=>'Thị xã Quảng Yên'],
            ['id'=>157, 'province_id'=>14, 'name'=>'Huyện Cô Tô'],
            ['id'=>158, 'province_id'=>15, 'name'=>'Thành phố Bắc Giang'],
            ['id'=>159, 'province_id'=>15, 'name'=>'Huyện Yên Thế'],
            ['id'=>160, 'province_id'=>15, 'name'=>'Huyện Tân Yên'],
            ['id'=>161, 'province_id'=>15, 'name'=>'Huyện Lạng Giang'],
            ['id'=>162, 'province_id'=>15, 'name'=>'Huyện Lục Nam'],
            ['id'=>163, 'province_id'=>15, 'name'=>'Huyện Lục Ngạn'],
            ['id'=>164, 'province_id'=>15, 'name'=>'Huyện Sơn Động'],
            ['id'=>165, 'province_id'=>15, 'name'=>'Huyện Yên Dũng'],
            ['id'=>166, 'province_id'=>15, 'name'=>'Huyện Việt Yên'],
            ['id'=>167, 'province_id'=>15, 'name'=>'Huyện Hiệp Hòa'],
            ['id'=>168, 'province_id'=>16, 'name'=>'Thành phố Việt Trì'],
            ['id'=>169, 'province_id'=>16, 'name'=>'Thị xã Phú Thọ'],
            ['id'=>170, 'province_id'=>16, 'name'=>'Huyện Đoan Hùng'],
            ['id'=>171, 'province_id'=>16, 'name'=>'Huyện Hạ Hoà'],
            ['id'=>172, 'province_id'=>16, 'name'=>'Huyện Thanh Ba'],
            ['id'=>173, 'province_id'=>16, 'name'=>'Huyện Phù Ninh'],
            ['id'=>174, 'province_id'=>16, 'name'=>'Huyện Yên Lập'],
            ['id'=>175, 'province_id'=>16, 'name'=>'Huyện Cẩm Khê'],
            ['id'=>176, 'province_id'=>16, 'name'=>'Huyện Tam Nông'],
            ['id'=>177, 'province_id'=>16, 'name'=>'Huyện Lâm Thao'],
            ['id'=>178, 'province_id'=>16, 'name'=>'Huyện Thanh Sơn'],
            ['id'=>179, 'province_id'=>16, 'name'=>'Huyện Thanh Thuỷ'],
            ['id'=>180, 'province_id'=>16, 'name'=>'Huyện Tân Sơn'],
            ['id'=>181, 'province_id'=>17, 'name'=>'Thành phố Vĩnh Yên'],
            ['id'=>182, 'province_id'=>17, 'name'=>'Thành phố Phúc Yên'],
            ['id'=>183, 'province_id'=>17, 'name'=>'Huyện Lập Thạch'],
            ['id'=>184, 'province_id'=>17, 'name'=>'Huyện Tam Dương'],
            ['id'=>185, 'province_id'=>17, 'name'=>'Huyện Tam Đảo'],
            ['id'=>186, 'province_id'=>17, 'name'=>'Huyện Bình Xuyên'],
            ['id'=>187, 'province_id'=>17, 'name'=>'Huyện Yên Lạc'],
            ['id'=>188, 'province_id'=>17, 'name'=>'Huyện Vĩnh Tường'],
            ['id'=>189, 'province_id'=>17, 'name'=>'Huyện Sông Lô'],
            ['id'=>190, 'province_id'=>18, 'name'=>'Thành phố Bắc Ninh'],
            ['id'=>191, 'province_id'=>18, 'name'=>'Huyện Yên Phong'],
            ['id'=>192, 'province_id'=>18, 'name'=>'Huyện Quế Võ'],
            ['id'=>193, 'province_id'=>18, 'name'=>'Huyện Tiên Du'],
            ['id'=>194, 'province_id'=>18, 'name'=>'Thành phố Từ Sơn'],
            ['id'=>195, 'province_id'=>18, 'name'=>'Huyện Thuận Thành'],
            ['id'=>196, 'province_id'=>18, 'name'=>'Huyện Gia Bình'],
            ['id'=>197, 'province_id'=>18, 'name'=>'Huyện Lương Tài'],
            ['id'=>198, 'province_id'=>19, 'name'=>'Thành phố Hải Dương'],
            ['id'=>199, 'province_id'=>19, 'name'=>'Thành phố Chí Linh'],
            ['id'=>200, 'province_id'=>19, 'name'=>'Huyện Nam Sách'],
            ['id'=>201, 'province_id'=>19, 'name'=>'Thị xã Kinh Môn'],
            ['id'=>202, 'province_id'=>19, 'name'=>'Huyện Kim Thành'],
            ['id'=>203, 'province_id'=>19, 'name'=>'Huyện Thanh Hà'],
            ['id'=>204, 'province_id'=>19, 'name'=>'Huyện Cẩm Giàng'],
            ['id'=>205, 'province_id'=>19, 'name'=>'Huyện Bình Giang'],
            ['id'=>206, 'province_id'=>19, 'name'=>'Huyện Gia Lộc'],
            ['id'=>207, 'province_id'=>19, 'name'=>'Huyện Tứ Kỳ'],
            ['id'=>208, 'province_id'=>19, 'name'=>'Huyện Ninh Giang'],
            ['id'=>209, 'province_id'=>19, 'name'=>'Huyện Thanh Miện'],
            ['id'=>210, 'province_id'=>20, 'name'=>'Quận Hồng Bàng'],
            ['id'=>211, 'province_id'=>20, 'name'=>'Quận Ngô Quyền'],
            ['id'=>212, 'province_id'=>20, 'name'=>'Quận Lê Chân'],
            ['id'=>213, 'province_id'=>20, 'name'=>'Quận Hải An'],
            ['id'=>214, 'province_id'=>20, 'name'=>'Quận Kiến An'],
            ['id'=>215, 'province_id'=>20, 'name'=>'Quận Đồ Sơn'],
            ['id'=>216, 'province_id'=>20, 'name'=>'Quận Dương Kinh'],
            ['id'=>217, 'province_id'=>20, 'name'=>'Huyện Thuỷ Nguyên'],
            ['id'=>218, 'province_id'=>20, 'name'=>'Huyện An Dương'],
            ['id'=>219, 'province_id'=>20, 'name'=>'Huyện An Lão'],
            ['id'=>220, 'province_id'=>20, 'name'=>'Huyện Kiến Thuỵ'],
            ['id'=>221, 'province_id'=>20, 'name'=>'Huyện Tiên Lãng'],
            ['id'=>222, 'province_id'=>20, 'name'=>'Huyện Vĩnh Bảo'],
            ['id'=>223, 'province_id'=>20, 'name'=>'Huyện Cát Hải'],
            ['id'=>224, 'province_id'=>20, 'name'=>'Huyện Bạch Long Vĩ'],
            ['id'=>225, 'province_id'=>21, 'name'=>'Thành phố Hưng Yên'],
            ['id'=>226, 'province_id'=>21, 'name'=>'Huyện Văn Lâm'],
            ['id'=>227, 'province_id'=>21, 'name'=>'Huyện Văn Giang'],
            ['id'=>228, 'province_id'=>21, 'name'=>'Huyện Yên Mỹ'],
            ['id'=>229, 'province_id'=>21, 'name'=>'Thị xã Mỹ Hào'],
            ['id'=>230, 'province_id'=>21, 'name'=>'Huyện Ân Thi'],
            ['id'=>231, 'province_id'=>21, 'name'=>'Huyện Khoái Châu'],
            ['id'=>232, 'province_id'=>21, 'name'=>'Huyện Kim Động'],
            ['id'=>233, 'province_id'=>21, 'name'=>'Huyện Tiên Lữ'],
            ['id'=>234, 'province_id'=>21, 'name'=>'Huyện Phù Cừ'],
            ['id'=>235, 'province_id'=>22, 'name'=>'Thành phố Thái Bình'],
            ['id'=>236, 'province_id'=>22, 'name'=>'Huyện Quỳnh Phụ'],
            ['id'=>237, 'province_id'=>22, 'name'=>'Huyện Hưng Hà'],
            ['id'=>238, 'province_id'=>22, 'name'=>'Huyện Đông Hưng'],
            ['id'=>239, 'province_id'=>22, 'name'=>'Huyện Thái Thụy'],
            ['id'=>240, 'province_id'=>22, 'name'=>'Huyện Tiền Hải'],
            ['id'=>241, 'province_id'=>22, 'name'=>'Huyện Kiến Xương'],
            ['id'=>242, 'province_id'=>22, 'name'=>'Huyện Vũ Thư'],
            ['id'=>243, 'province_id'=>23, 'name'=>'Thành phố Phủ Lý'],
            ['id'=>244, 'province_id'=>23, 'name'=>'Thị xã Duy Tiên'],
            ['id'=>245, 'province_id'=>23, 'name'=>'Huyện Kim Bảng'],
            ['id'=>246, 'province_id'=>23, 'name'=>'Huyện Thanh Liêm'],
            ['id'=>247, 'province_id'=>23, 'name'=>'Huyện Bình Lục'],
            ['id'=>248, 'province_id'=>23, 'name'=>'Huyện Lý Nhân'],
            ['id'=>249, 'province_id'=>24, 'name'=>'Thành phố Nam Định'],
            ['id'=>250, 'province_id'=>24, 'name'=>'Huyện Mỹ Lộc'],
            ['id'=>251, 'province_id'=>24, 'name'=>'Huyện Vụ Bản'],
            ['id'=>252, 'province_id'=>24, 'name'=>'Huyện Ý Yên'],
            ['id'=>253, 'province_id'=>24, 'name'=>'Huyện Nghĩa Hưng'],
            ['id'=>254, 'province_id'=>24, 'name'=>'Huyện Nam Trực'],
            ['id'=>255, 'province_id'=>24, 'name'=>'Huyện Trực Ninh'],
            ['id'=>256, 'province_id'=>24, 'name'=>'Huyện Xuân Trường'],
            ['id'=>257, 'province_id'=>24, 'name'=>'Huyện Giao Thủy'],
            ['id'=>258, 'province_id'=>24, 'name'=>'Huyện Hải Hậu'],
            ['id'=>259, 'province_id'=>25, 'name'=>'Thành phố Ninh Bình'],
            ['id'=>260, 'province_id'=>25, 'name'=>'Thành phố Tam Điệp'],
            ['id'=>261, 'province_id'=>25, 'name'=>'Huyện Nho Quan'],
            ['id'=>262, 'province_id'=>25, 'name'=>'Huyện Gia Viễn'],
            ['id'=>263, 'province_id'=>25, 'name'=>'Huyện Hoa Lư'],
            ['id'=>264, 'province_id'=>25, 'name'=>'Huyện Yên Khánh'],
            ['id'=>265, 'province_id'=>25, 'name'=>'Huyện Kim Sơn'],
            ['id'=>266, 'province_id'=>25, 'name'=>'Huyện Yên Mô'],
            ['id'=>267, 'province_id'=>26, 'name'=>'Thành phố Thanh Hóa'],
            ['id'=>268, 'province_id'=>26, 'name'=>'Thị xã Bỉm Sơn'],
            ['id'=>269, 'province_id'=>26, 'name'=>'Thành phố Sầm Sơn'],
            ['id'=>270, 'province_id'=>26, 'name'=>'Huyện Mường Lát'],
            ['id'=>271, 'province_id'=>26, 'name'=>'Huyện Quan Hóa'],
            ['id'=>272, 'province_id'=>26, 'name'=>'Huyện Bá Thước'],
            ['id'=>273, 'province_id'=>26, 'name'=>'Huyện Quan Sơn'],
            ['id'=>274, 'province_id'=>26, 'name'=>'Huyện Lang Chánh'],
            ['id'=>275, 'province_id'=>26, 'name'=>'Huyện Ngọc Lặc'],
            ['id'=>276, 'province_id'=>26, 'name'=>'Huyện Cẩm Thủy'],
            ['id'=>277, 'province_id'=>26, 'name'=>'Huyện Thạch Thành'],
            ['id'=>278, 'province_id'=>26, 'name'=>'Huyện Hà Trung'],
            ['id'=>279, 'province_id'=>26, 'name'=>'Huyện Vĩnh Lộc'],
            ['id'=>280, 'province_id'=>26, 'name'=>'Huyện Yên Định'],
            ['id'=>281, 'province_id'=>26, 'name'=>'Huyện Thọ Xuân'],
            ['id'=>282, 'province_id'=>26, 'name'=>'Huyện Thường Xuân'],
            ['id'=>283, 'province_id'=>26, 'name'=>'Huyện Triệu Sơn'],
            ['id'=>284, 'province_id'=>26, 'name'=>'Huyện Thiệu Hóa'],
            ['id'=>285, 'province_id'=>26, 'name'=>'Huyện Hoằng Hóa'],
            ['id'=>286, 'province_id'=>26, 'name'=>'Huyện Hậu Lộc'],
            ['id'=>287, 'province_id'=>26, 'name'=>'Huyện Nga Sơn'],
            ['id'=>288, 'province_id'=>26, 'name'=>'Huyện Như Xuân'],
            ['id'=>289, 'province_id'=>26, 'name'=>'Huyện Như Thanh'],
            ['id'=>290, 'province_id'=>26, 'name'=>'Huyện Nông Cống'],
            ['id'=>291, 'province_id'=>26, 'name'=>'Huyện Đông Sơn'],
            ['id'=>292, 'province_id'=>26, 'name'=>'Huyện Quảng Xương'],
            ['id'=>293, 'province_id'=>26, 'name'=>'Thị xã Nghi Sơn'],
            ['id'=>294, 'province_id'=>27, 'name'=>'Thành phố Vinh'],
            ['id'=>295, 'province_id'=>27, 'name'=>'Thị xã Cửa Lò'],
            ['id'=>296, 'province_id'=>27, 'name'=>'Thị xã Thái Hoà'],
            ['id'=>297, 'province_id'=>27, 'name'=>'Huyện Quế Phong'],
            ['id'=>298, 'province_id'=>27, 'name'=>'Huyện Quỳ Châu'],
            ['id'=>299, 'province_id'=>27, 'name'=>'Huyện Kỳ Sơn'],
            ['id'=>300, 'province_id'=>27, 'name'=>'Huyện Tương Dương'],
            ['id'=>301, 'province_id'=>27, 'name'=>'Huyện Nghĩa Đàn'],
            ['id'=>302, 'province_id'=>27, 'name'=>'Huyện Quỳ Hợp'],
            ['id'=>303, 'province_id'=>27, 'name'=>'Huyện Quỳnh Lưu'],
            ['id'=>304, 'province_id'=>27, 'name'=>'Huyện Con Cuông'],
            ['id'=>305, 'province_id'=>27, 'name'=>'Huyện Tân Kỳ'],
            ['id'=>306, 'province_id'=>27, 'name'=>'Huyện Anh Sơn'],
            ['id'=>307, 'province_id'=>27, 'name'=>'Huyện Diễn Châu'],
            ['id'=>308, 'province_id'=>27, 'name'=>'Huyện Yên Thành'],
            ['id'=>309, 'province_id'=>27, 'name'=>'Huyện Đô Lương'],
            ['id'=>310, 'province_id'=>27, 'name'=>'Huyện Thanh Chương'],
            ['id'=>311, 'province_id'=>27, 'name'=>'Huyện Nghi Lộc'],
            ['id'=>312, 'province_id'=>27, 'name'=>'Huyện Nam Đàn'],
            ['id'=>313, 'province_id'=>27, 'name'=>'Huyện Hưng Nguyên'],
            ['id'=>314, 'province_id'=>27, 'name'=>'Thị xã Hoàng Mai'],
            ['id'=>315, 'province_id'=>28, 'name'=>'Thành phố Hà Tĩnh'],
            ['id'=>316, 'province_id'=>28, 'name'=>'Thị xã Hồng Lĩnh'],
            ['id'=>317, 'province_id'=>28, 'name'=>'Huyện Hương Sơn'],
            ['id'=>318, 'province_id'=>28, 'name'=>'Huyện Đức Thọ'],
            ['id'=>319, 'province_id'=>28, 'name'=>'Huyện Vũ Quang'],
            ['id'=>320, 'province_id'=>28, 'name'=>'Huyện Nghi Xuân'],
            ['id'=>321, 'province_id'=>28, 'name'=>'Huyện Can Lộc'],
            ['id'=>322, 'province_id'=>28, 'name'=>'Huyện Hương Khê'],
            ['id'=>323, 'province_id'=>28, 'name'=>'Huyện Thạch Hà'],
            ['id'=>324, 'province_id'=>28, 'name'=>'Huyện Cẩm Xuyên'],
            ['id'=>325, 'province_id'=>28, 'name'=>'Huyện Kỳ Anh'],
            ['id'=>326, 'province_id'=>28, 'name'=>'Huyện Lộc Hà'],
            ['id'=>327, 'province_id'=>28, 'name'=>'Thị xã Kỳ Anh'],
            ['id'=>328, 'province_id'=>29, 'name'=>'Thành Phố Đồng Hới'],
            ['id'=>329, 'province_id'=>29, 'name'=>'Huyện Minh Hóa'],
            ['id'=>330, 'province_id'=>29, 'name'=>'Huyện Tuyên Hóa'],
            ['id'=>331, 'province_id'=>29, 'name'=>'Huyện Quảng Trạch'],
            ['id'=>332, 'province_id'=>29, 'name'=>'Huyện Bố Trạch'],
            ['id'=>333, 'province_id'=>29, 'name'=>'Huyện Quảng Ninh'],
            ['id'=>334, 'province_id'=>29, 'name'=>'Huyện Lệ Thủy'],
            ['id'=>335, 'province_id'=>29, 'name'=>'Thị xã Ba Đồn'],
            ['id'=>336, 'province_id'=>30, 'name'=>'Thành phố Đông Hà'],
            ['id'=>337, 'province_id'=>30, 'name'=>'Thị xã Quảng Trị'],
            ['id'=>338, 'province_id'=>30, 'name'=>'Huyện Vĩnh Linh'],
            ['id'=>339, 'province_id'=>30, 'name'=>'Huyện Hướng Hóa'],
            ['id'=>340, 'province_id'=>30, 'name'=>'Huyện Gio Linh'],
            ['id'=>341, 'province_id'=>30, 'name'=>'Huyện Đa Krông'],
            ['id'=>342, 'province_id'=>30, 'name'=>'Huyện Cam Lộ'],
            ['id'=>343, 'province_id'=>30, 'name'=>'Huyện Triệu Phong'],
            ['id'=>344, 'province_id'=>30, 'name'=>'Huyện Hải Lăng'],
            ['id'=>345, 'province_id'=>30, 'name'=>'Huyện Cồn Cỏ'],
            ['id'=>346, 'province_id'=>31, 'name'=>'Thành phố Huế'],
            ['id'=>347, 'province_id'=>31, 'name'=>'Huyện Phong Điền'],
            ['id'=>348, 'province_id'=>31, 'name'=>'Huyện Quảng Điền'],
            ['id'=>349, 'province_id'=>31, 'name'=>'Huyện Phú Vang'],
            ['id'=>350, 'province_id'=>31, 'name'=>'Thị xã Hương Thủy'],
            ['id'=>351, 'province_id'=>31, 'name'=>'Thị xã Hương Trà'],
            ['id'=>352, 'province_id'=>31, 'name'=>'Huyện A Lưới'],
            ['id'=>353, 'province_id'=>31, 'name'=>'Huyện Phú Lộc'],
            ['id'=>354, 'province_id'=>31, 'name'=>'Huyện Nam Đông'],
            ['id'=>355, 'province_id'=>32, 'name'=>'Quận Liên Chiểu'],
            ['id'=>356, 'province_id'=>32, 'name'=>'Quận Thanh Khê'],
            ['id'=>357, 'province_id'=>32, 'name'=>'Quận Hải Châu'],
            ['id'=>358, 'province_id'=>32, 'name'=>'Quận Sơn Trà'],
            ['id'=>359, 'province_id'=>32, 'name'=>'Quận Ngũ Hành Sơn'],
            ['id'=>360, 'province_id'=>32, 'name'=>'Quận Cẩm Lệ'],
            ['id'=>361, 'province_id'=>32, 'name'=>'Huyện Hòa Vang'],
            ['id'=>362, 'province_id'=>32, 'name'=>'Huyện Hoàng Sa'],
            ['id'=>363, 'province_id'=>33, 'name'=>'Thành phố Tam Kỳ'],
            ['id'=>364, 'province_id'=>33, 'name'=>'Thành phố Hội An'],
            ['id'=>365, 'province_id'=>33, 'name'=>'Huyện Tây Giang'],
            ['id'=>366, 'province_id'=>33, 'name'=>'Huyện Đông Giang'],
            ['id'=>367, 'province_id'=>33, 'name'=>'Huyện Đại Lộc'],
            ['id'=>368, 'province_id'=>33, 'name'=>'Thị xã Điện Bàn'],
            ['id'=>369, 'province_id'=>33, 'name'=>'Huyện Duy Xuyên'],
            ['id'=>370, 'province_id'=>33, 'name'=>'Huyện Quế Sơn'],
            ['id'=>371, 'province_id'=>33, 'name'=>'Huyện Nam Giang'],
            ['id'=>372, 'province_id'=>33, 'name'=>'Huyện Phước Sơn'],
            ['id'=>373, 'province_id'=>33, 'name'=>'Huyện Hiệp Đức'],
            ['id'=>374, 'province_id'=>33, 'name'=>'Huyện Thăng Bình'],
            ['id'=>375, 'province_id'=>33, 'name'=>'Huyện Tiên Phước'],
            ['id'=>376, 'province_id'=>33, 'name'=>'Huyện Bắc Trà My'],
            ['id'=>377, 'province_id'=>33, 'name'=>'Huyện Nam Trà My'],
            ['id'=>378, 'province_id'=>33, 'name'=>'Huyện Núi Thành'],
            ['id'=>379, 'province_id'=>33, 'name'=>'Huyện Phú Ninh'],
            ['id'=>380, 'province_id'=>33, 'name'=>'Huyện Nông Sơn'],
            ['id'=>381, 'province_id'=>34, 'name'=>'Thành phố Quảng Ngãi'],
            ['id'=>382, 'province_id'=>34, 'name'=>'Huyện Bình Sơn'],
            ['id'=>383, 'province_id'=>34, 'name'=>'Huyện Trà Bồng'],
            ['id'=>384, 'province_id'=>34, 'name'=>'Huyện Sơn Tịnh'],
            ['id'=>385, 'province_id'=>34, 'name'=>'Huyện Tư Nghĩa'],
            ['id'=>386, 'province_id'=>34, 'name'=>'Huyện Sơn Hà'],
            ['id'=>387, 'province_id'=>34, 'name'=>'Huyện Sơn Tây'],
            ['id'=>388, 'province_id'=>34, 'name'=>'Huyện Minh Long'],
            ['id'=>389, 'province_id'=>34, 'name'=>'Huyện Nghĩa Hành'],
            ['id'=>390, 'province_id'=>34, 'name'=>'Huyện Mộ Đức'],
            ['id'=>391, 'province_id'=>34, 'name'=>'Thị xã Đức Phổ'],
            ['id'=>392, 'province_id'=>34, 'name'=>'Huyện Ba Tơ'],
            ['id'=>393, 'province_id'=>34, 'name'=>'Huyện Lý Sơn'],
            ['id'=>394, 'province_id'=>35, 'name'=>'Thành phố Quy Nhơn'],
            ['id'=>395, 'province_id'=>35, 'name'=>'Huyện An Lão'],
            ['id'=>396, 'province_id'=>35, 'name'=>'Thị xã Hoài Nhơn'],
            ['id'=>397, 'province_id'=>35, 'name'=>'Huyện Hoài Ân'],
            ['id'=>398, 'province_id'=>35, 'name'=>'Huyện Phù Mỹ'],
            ['id'=>399, 'province_id'=>35, 'name'=>'Huyện Vĩnh Thạnh'],
            ['id'=>400, 'province_id'=>35, 'name'=>'Huyện Tây Sơn'],
            ['id'=>401, 'province_id'=>35, 'name'=>'Huyện Phù Cát'],
            ['id'=>402, 'province_id'=>35, 'name'=>'Thị xã An Nhơn'],
            ['id'=>403, 'province_id'=>35, 'name'=>'Huyện Tuy Phước'],
            ['id'=>404, 'province_id'=>35, 'name'=>'Huyện Vân Canh'],
            ['id'=>405, 'province_id'=>36, 'name'=>'Thành phố Tuy Hoà'],
            ['id'=>406, 'province_id'=>36, 'name'=>'Thị xã Sông Cầu'],
            ['id'=>407, 'province_id'=>36, 'name'=>'Huyện Đồng Xuân'],
            ['id'=>408, 'province_id'=>36, 'name'=>'Huyện Tuy An'],
            ['id'=>409, 'province_id'=>36, 'name'=>'Huyện Sơn Hòa'],
            ['id'=>410, 'province_id'=>36, 'name'=>'Huyện Sông Hinh'],
            ['id'=>411, 'province_id'=>36, 'name'=>'Huyện Tây Hoà'],
            ['id'=>412, 'province_id'=>36, 'name'=>'Huyện Phú Hoà'],
            ['id'=>413, 'province_id'=>36, 'name'=>'Thị xã Đông Hòa'],
            ['id'=>414, 'province_id'=>37, 'name'=>'Thành phố Nha Trang'],
            ['id'=>415, 'province_id'=>37, 'name'=>'Thành phố Cam Ranh'],
            ['id'=>416, 'province_id'=>37, 'name'=>'Huyện Cam Lâm'],
            ['id'=>417, 'province_id'=>37, 'name'=>'Huyện Vạn Ninh'],
            ['id'=>418, 'province_id'=>37, 'name'=>'Thị xã Ninh Hòa'],
            ['id'=>419, 'province_id'=>37, 'name'=>'Huyện Khánh Vĩnh'],
            ['id'=>420, 'province_id'=>37, 'name'=>'Huyện Diên Khánh'],
            ['id'=>421, 'province_id'=>37, 'name'=>'Huyện Khánh Sơn'],
            ['id'=>422, 'province_id'=>37, 'name'=>'Huyện Trường Sa'],
            ['id'=>423, 'province_id'=>38, 'name'=>'Thành phố Phan Rang-Tháp Chàm'],
            ['id'=>424, 'province_id'=>38, 'name'=>'Huyện Bác Ái'],
            ['id'=>425, 'province_id'=>38, 'name'=>'Huyện Ninh Sơn'],
            ['id'=>426, 'province_id'=>38, 'name'=>'Huyện Ninh Hải'],
            ['id'=>427, 'province_id'=>38, 'name'=>'Huyện Ninh Phước'],
            ['id'=>428, 'province_id'=>38, 'name'=>'Huyện Thuận Bắc'],
            ['id'=>429, 'province_id'=>38, 'name'=>'Huyện Thuận Nam'],
            ['id'=>430, 'province_id'=>39, 'name'=>'Thành phố Phan Thiết'],
            ['id'=>431, 'province_id'=>39, 'name'=>'Thị xã La Gi'],
            ['id'=>432, 'province_id'=>39, 'name'=>'Huyện Tuy Phong'],
            ['id'=>433, 'province_id'=>39, 'name'=>'Huyện Bắc Bình'],
            ['id'=>434, 'province_id'=>39, 'name'=>'Huyện Hàm Thuận Bắc'],
            ['id'=>435, 'province_id'=>39, 'name'=>'Huyện Hàm Thuận Nam'],
            ['id'=>436, 'province_id'=>39, 'name'=>'Huyện Tánh Linh'],
            ['id'=>437, 'province_id'=>39, 'name'=>'Huyện Đức Linh'],
            ['id'=>438, 'province_id'=>39, 'name'=>'Huyện Hàm Tân'],
            ['id'=>439, 'province_id'=>39, 'name'=>'Huyện Phú Quí'],
            ['id'=>440, 'province_id'=>40, 'name'=>'Thành phố Kon Tum'],
            ['id'=>441, 'province_id'=>40, 'name'=>'Huyện Đắk Glei'],
            ['id'=>442, 'province_id'=>40, 'name'=>'Huyện Ngọc Hồi'],
            ['id'=>443, 'province_id'=>40, 'name'=>'Huyện Đắk Tô'],
            ['id'=>444, 'province_id'=>40, 'name'=>'Huyện Kon Plông'],
            ['id'=>445, 'province_id'=>40, 'name'=>'Huyện Kon Rẫy'],
            ['id'=>446, 'province_id'=>40, 'name'=>'Huyện Đắk Hà'],
            ['id'=>447, 'province_id'=>40, 'name'=>'Huyện Sa Thầy'],
            ['id'=>448, 'province_id'=>40, 'name'=>'Huyện Tu Mơ Rông'],
            ['id'=>449, 'province_id'=>40, 'name'=>'Huyện Ia H\' Drai'],
            ['id'=>450, 'province_id'=>41, 'name'=>'Thành phố Pleiku'],
            ['id'=>451, 'province_id'=>41, 'name'=>'Thị xã An Khê'],
            ['id'=>452, 'province_id'=>41, 'name'=>'Thị xã Ayun Pa'],
            ['id'=>453, 'province_id'=>41, 'name'=>'Huyện KBang'],
            ['id'=>454, 'province_id'=>41, 'name'=>'Huyện Đăk Đoa'],
            ['id'=>455, 'province_id'=>41, 'name'=>'Huyện Chư Păh'],
            ['id'=>456, 'province_id'=>41, 'name'=>'Huyện Ia Grai'],
            ['id'=>457, 'province_id'=>41, 'name'=>'Huyện Mang Yang'],
            ['id'=>458, 'province_id'=>41, 'name'=>'Huyện Kông Chro'],
            ['id'=>459, 'province_id'=>41, 'name'=>'Huyện Đức Cơ'],
            ['id'=>460, 'province_id'=>41, 'name'=>'Huyện Chư Prông'],
            ['id'=>461, 'province_id'=>41, 'name'=>'Huyện Chư Sê'],
            ['id'=>462, 'province_id'=>41, 'name'=>'Huyện Đăk Pơ'],
            ['id'=>463, 'province_id'=>41, 'name'=>'Huyện Ia Pa'],
            ['id'=>464, 'province_id'=>41, 'name'=>'Huyện Krông Pa'],
            ['id'=>465, 'province_id'=>41, 'name'=>'Huyện Phú Thiện'],
            ['id'=>466, 'province_id'=>41, 'name'=>'Huyện Chư Pưh'],
            ['id'=>467, 'province_id'=>42, 'name'=>'Thành phố Buôn Ma Thuột'],
            ['id'=>468, 'province_id'=>42, 'name'=>'Thị Xã Buôn Hồ'],
            ['id'=>469, 'province_id'=>42, 'name'=>'Huyện Ea H\'leo'],
            ['id'=>470, 'province_id'=>42, 'name'=>'Huyện Ea Súp'],
            ['id'=>471, 'province_id'=>42, 'name'=>'Huyện Buôn Đôn'],
            ['id'=>472, 'province_id'=>42, 'name'=>'Huyện Cư M\'gar'],
            ['id'=>473, 'province_id'=>42, 'name'=>'Huyện Krông Búk'],
            ['id'=>474, 'province_id'=>42, 'name'=>'Huyện Krông Năng'],
            ['id'=>475, 'province_id'=>42, 'name'=>'Huyện Ea Kar'],
            ['id'=>476, 'province_id'=>42, 'name'=>'Huyện M\'Đrắk'],
            ['id'=>477, 'province_id'=>42, 'name'=>'Huyện Krông Bông'],
            ['id'=>478, 'province_id'=>42, 'name'=>'Huyện Krông Pắc'],
            ['id'=>479, 'province_id'=>42, 'name'=>'Huyện Krông A Na'],
            ['id'=>480, 'province_id'=>42, 'name'=>'Huyện Lắk'],
            ['id'=>481, 'province_id'=>42, 'name'=>'Huyện Cư Kuin'],
            ['id'=>482, 'province_id'=>43, 'name'=>'Thành phố Gia Nghĩa'],
            ['id'=>483, 'province_id'=>43, 'name'=>'Huyện Đăk Glong'],
            ['id'=>484, 'province_id'=>43, 'name'=>'Huyện Cư Jút'],
            ['id'=>485, 'province_id'=>43, 'name'=>'Huyện Đắk Mil'],
            ['id'=>486, 'province_id'=>43, 'name'=>'Huyện Krông Nô'],
            ['id'=>487, 'province_id'=>43, 'name'=>'Huyện Đắk Song'],
            ['id'=>488, 'province_id'=>43, 'name'=>'Huyện Đắk R\'Lấp'],
            ['id'=>489, 'province_id'=>43, 'name'=>'Huyện Tuy Đức'],
            ['id'=>490, 'province_id'=>44, 'name'=>'Thành phố Đà Lạt'],
            ['id'=>491, 'province_id'=>44, 'name'=>'Thành phố Bảo Lộc'],
            ['id'=>492, 'province_id'=>44, 'name'=>'Huyện Đam Rông'],
            ['id'=>493, 'province_id'=>44, 'name'=>'Huyện Lạc Dương'],
            ['id'=>494, 'province_id'=>44, 'name'=>'Huyện Lâm Hà'],
            ['id'=>495, 'province_id'=>44, 'name'=>'Huyện Đơn Dương'],
            ['id'=>496, 'province_id'=>44, 'name'=>'Huyện Đức Trọng'],
            ['id'=>497, 'province_id'=>44, 'name'=>'Huyện Di Linh'],
            ['id'=>498, 'province_id'=>44, 'name'=>'Huyện Bảo Lâm'],
            ['id'=>499, 'province_id'=>44, 'name'=>'Huyện Đạ Huoai'],
            ['id'=>500, 'province_id'=>44, 'name'=>'Huyện Đạ Tẻh'],
            ['id'=>501, 'province_id'=>44, 'name'=>'Huyện Cát Tiên'],
            ['id'=>502, 'province_id'=>45, 'name'=>'Thị xã Phước Long'],
            ['id'=>503, 'province_id'=>45, 'name'=>'Thành phố Đồng Xoài'],
            ['id'=>504, 'province_id'=>45, 'name'=>'Thị xã Bình Long'],
            ['id'=>505, 'province_id'=>45, 'name'=>'Huyện Bù Gia Mập'],
            ['id'=>506, 'province_id'=>45, 'name'=>'Huyện Lộc Ninh'],
            ['id'=>507, 'province_id'=>45, 'name'=>'Huyện Bù Đốp'],
            ['id'=>508, 'province_id'=>45, 'name'=>'Huyện Hớn Quản'],
            ['id'=>509, 'province_id'=>45, 'name'=>'Huyện Đồng Phú'],
            ['id'=>510, 'province_id'=>45, 'name'=>'Huyện Bù Đăng'],
            ['id'=>511, 'province_id'=>45, 'name'=>'Huyện Chơn Thành'],
            ['id'=>512, 'province_id'=>45, 'name'=>'Huyện Phú Riềng'],
            ['id'=>513, 'province_id'=>46, 'name'=>'Thành phố Tây Ninh'],
            ['id'=>514, 'province_id'=>46, 'name'=>'Huyện Tân Biên'],
            ['id'=>515, 'province_id'=>46, 'name'=>'Huyện Tân Châu'],
            ['id'=>516, 'province_id'=>46, 'name'=>'Huyện Dương Minh Châu'],
            ['id'=>517, 'province_id'=>46, 'name'=>'Huyện Châu Thành'],
            ['id'=>518, 'province_id'=>46, 'name'=>'Thị xã Hòa Thành'],
            ['id'=>519, 'province_id'=>46, 'name'=>'Huyện Gò Dầu'],
            ['id'=>520, 'province_id'=>46, 'name'=>'Huyện Bến Cầu'],
            ['id'=>521, 'province_id'=>46, 'name'=>'Thị xã Trảng Bàng'],
            ['id'=>522, 'province_id'=>47, 'name'=>'Thành phố Thủ Dầu Một'],
            ['id'=>523, 'province_id'=>47, 'name'=>'Huyện Bàu Bàng'],
            ['id'=>524, 'province_id'=>47, 'name'=>'Huyện Dầu Tiếng'],
            ['id'=>525, 'province_id'=>47, 'name'=>'Thị xã Bến Cát'],
            ['id'=>526, 'province_id'=>47, 'name'=>'Huyện Phú Giáo'],
            ['id'=>527, 'province_id'=>47, 'name'=>'Thị xã Tân Uyên'],
            ['id'=>528, 'province_id'=>47, 'name'=>'Thành phố Dĩ An'],
            ['id'=>529, 'province_id'=>47, 'name'=>'Thành phố Thuận An'],
            ['id'=>530, 'province_id'=>47, 'name'=>'Huyện Bắc Tân Uyên'],
            ['id'=>531, 'province_id'=>48, 'name'=>'Thành phố Biên Hòa'],
            ['id'=>532, 'province_id'=>48, 'name'=>'Thành phố Long Khánh'],
            ['id'=>533, 'province_id'=>48, 'name'=>'Huyện Tân Phú'],
            ['id'=>534, 'province_id'=>48, 'name'=>'Huyện Vĩnh Cửu'],
            ['id'=>535, 'province_id'=>48, 'name'=>'Huyện Định Quán'],
            ['id'=>536, 'province_id'=>48, 'name'=>'Huyện Trảng Bom'],
            ['id'=>537, 'province_id'=>48, 'name'=>'Huyện Thống Nhất'],
            ['id'=>538, 'province_id'=>48, 'name'=>'Huyện Cẩm Mỹ'],
            ['id'=>539, 'province_id'=>48, 'name'=>'Huyện Long Thành'],
            ['id'=>540, 'province_id'=>48, 'name'=>'Huyện Xuân Lộc'],
            ['id'=>541, 'province_id'=>48, 'name'=>'Huyện Nhơn Trạch'],
            ['id'=>542, 'province_id'=>49, 'name'=>'Thành phố Vũng Tàu'],
            ['id'=>543, 'province_id'=>49, 'name'=>'Thành phố Bà Rịa'],
            ['id'=>544, 'province_id'=>49, 'name'=>'Huyện Châu Đức'],
            ['id'=>545, 'province_id'=>49, 'name'=>'Huyện Xuyên Mộc'],
            ['id'=>546, 'province_id'=>49, 'name'=>'Huyện Long Điền'],
            ['id'=>547, 'province_id'=>49, 'name'=>'Huyện Đất Đỏ'],
            ['id'=>548, 'province_id'=>49, 'name'=>'Thị xã Phú Mỹ'],
            ['id'=>549, 'province_id'=>49, 'name'=>'Huyện Côn Đảo'],
            ['id'=>550, 'province_id'=>50, 'name'=>'Quận 1'],
            ['id'=>551, 'province_id'=>50, 'name'=>'Quận 12'],
            ['id'=>552, 'province_id'=>50, 'name'=>'Quận Gò Vấp'],
            ['id'=>553, 'province_id'=>50, 'name'=>'Quận Bình Thạnh'],
            ['id'=>554, 'province_id'=>50, 'name'=>'Quận Tân Bình'],
            ['id'=>555, 'province_id'=>50, 'name'=>'Quận Tân Phú'],
            ['id'=>556, 'province_id'=>50, 'name'=>'Quận Phú Nhuận'],
            ['id'=>557, 'province_id'=>50, 'name'=>'Thành phố Thủ Đức'],
            ['id'=>558, 'province_id'=>50, 'name'=>'Quận 3'],
            ['id'=>559, 'province_id'=>50, 'name'=>'Quận 10'],
            ['id'=>560, 'province_id'=>50, 'name'=>'Quận 11'],
            ['id'=>561, 'province_id'=>50, 'name'=>'Quận 4'],
            ['id'=>562, 'province_id'=>50, 'name'=>'Quận 5'],
            ['id'=>563, 'province_id'=>50, 'name'=>'Quận 6'],
            ['id'=>564, 'province_id'=>50, 'name'=>'Quận 8'],
            ['id'=>565, 'province_id'=>50, 'name'=>'Quận Bình Tân'],
            ['id'=>566, 'province_id'=>50, 'name'=>'Quận 7'],
            ['id'=>567, 'province_id'=>50, 'name'=>'Huyện Củ Chi'],
            ['id'=>568, 'province_id'=>50, 'name'=>'Huyện Hóc Môn'],
            ['id'=>569, 'province_id'=>50, 'name'=>'Huyện Bình Chánh'],
            ['id'=>570, 'province_id'=>50, 'name'=>'Huyện Nhà Bè'],
            ['id'=>571, 'province_id'=>50, 'name'=>'Huyện Cần Giờ'],
            ['id'=>572, 'province_id'=>51, 'name'=>'Thành phố Tân An'],
            ['id'=>573, 'province_id'=>51, 'name'=>'Thị xã Kiến Tường'],
            ['id'=>574, 'province_id'=>51, 'name'=>'Huyện Tân Hưng'],
            ['id'=>575, 'province_id'=>51, 'name'=>'Huyện Vĩnh Hưng'],
            ['id'=>576, 'province_id'=>51, 'name'=>'Huyện Mộc Hóa'],
            ['id'=>577, 'province_id'=>51, 'name'=>'Huyện Tân Thạnh'],
            ['id'=>578, 'province_id'=>51, 'name'=>'Huyện Thạnh Hóa'],
            ['id'=>579, 'province_id'=>51, 'name'=>'Huyện Đức Huệ'],
            ['id'=>580, 'province_id'=>51, 'name'=>'Huyện Đức Hòa'],
            ['id'=>581, 'province_id'=>51, 'name'=>'Huyện Bến Lức'],
            ['id'=>582, 'province_id'=>51, 'name'=>'Huyện Thủ Thừa'],
            ['id'=>583, 'province_id'=>51, 'name'=>'Huyện Tân Trụ'],
            ['id'=>584, 'province_id'=>51, 'name'=>'Huyện Cần Đước'],
            ['id'=>585, 'province_id'=>51, 'name'=>'Huyện Cần Giuộc'],
            ['id'=>586, 'province_id'=>51, 'name'=>'Huyện Châu Thành'],
            ['id'=>587, 'province_id'=>52, 'name'=>'Thành phố Mỹ Tho'],
            ['id'=>588, 'province_id'=>52, 'name'=>'Thị xã Gò Công'],
            ['id'=>589, 'province_id'=>52, 'name'=>'Thị xã Cai Lậy'],
            ['id'=>590, 'province_id'=>52, 'name'=>'Huyện Tân Phước'],
            ['id'=>591, 'province_id'=>52, 'name'=>'Huyện Cái Bè'],
            ['id'=>592, 'province_id'=>52, 'name'=>'Huyện Cai Lậy'],
            ['id'=>593, 'province_id'=>52, 'name'=>'Huyện Châu Thành'],
            ['id'=>594, 'province_id'=>52, 'name'=>'Huyện Chợ Gạo'],
            ['id'=>595, 'province_id'=>52, 'name'=>'Huyện Gò Công Tây'],
            ['id'=>596, 'province_id'=>52, 'name'=>'Huyện Gò Công Đông'],
            ['id'=>597, 'province_id'=>52, 'name'=>'Huyện Tân Phú Đông'],
            ['id'=>598, 'province_id'=>53, 'name'=>'Thành phố Bến Tre'],
            ['id'=>599, 'province_id'=>53, 'name'=>'Huyện Châu Thành'],
            ['id'=>600, 'province_id'=>53, 'name'=>'Huyện Chợ Lách'],
            ['id'=>601, 'province_id'=>53, 'name'=>'Huyện Mỏ Cày Nam'],
            ['id'=>602, 'province_id'=>53, 'name'=>'Huyện Giồng Trôm'],
            ['id'=>603, 'province_id'=>53, 'name'=>'Huyện Bình Đại'],
            ['id'=>604, 'province_id'=>53, 'name'=>'Huyện Ba Tri'],
            ['id'=>605, 'province_id'=>53, 'name'=>'Huyện Thạnh Phú'],
            ['id'=>606, 'province_id'=>53, 'name'=>'Huyện Mỏ Cày Bắc'],
            ['id'=>607, 'province_id'=>54, 'name'=>'Thành phố Trà Vinh'],
            ['id'=>608, 'province_id'=>54, 'name'=>'Huyện Càng Long'],
            ['id'=>609, 'province_id'=>54, 'name'=>'Huyện Cầu Kè'],
            ['id'=>610, 'province_id'=>54, 'name'=>'Huyện Tiểu Cần'],
            ['id'=>611, 'province_id'=>54, 'name'=>'Huyện Châu Thành'],
            ['id'=>612, 'province_id'=>54, 'name'=>'Huyện Cầu Ngang'],
            ['id'=>613, 'province_id'=>54, 'name'=>'Huyện Trà Cú'],
            ['id'=>614, 'province_id'=>54, 'name'=>'Huyện Duyên Hải'],
            ['id'=>615, 'province_id'=>54, 'name'=>'Thị xã Duyên Hải'],
            ['id'=>616, 'province_id'=>55, 'name'=>'Thành phố Vĩnh Long'],
            ['id'=>617, 'province_id'=>55, 'name'=>'Huyện Long Hồ'],
            ['id'=>618, 'province_id'=>55, 'name'=>'Huyện Mang Thít'],
            ['id'=>619, 'province_id'=>55, 'name'=>'Huyện  Vũng Liêm'],
            ['id'=>620, 'province_id'=>55, 'name'=>'Huyện Tam Bình'],
            ['id'=>621, 'province_id'=>55, 'name'=>'Thị xã Bình Minh'],
            ['id'=>622, 'province_id'=>55, 'name'=>'Huyện Trà Ôn'],
            ['id'=>623, 'province_id'=>55, 'name'=>'Huyện Bình Tân'],
            ['id'=>624, 'province_id'=>56, 'name'=>'Thành phố Cao Lãnh'],
            ['id'=>625, 'province_id'=>56, 'name'=>'Thành phố Sa Đéc'],
            ['id'=>626, 'province_id'=>56, 'name'=>'Thành phố Hồng Ngự'],
            ['id'=>627, 'province_id'=>56, 'name'=>'Huyện Tân Hồng'],
            ['id'=>628, 'province_id'=>56, 'name'=>'Huyện Hồng Ngự'],
            ['id'=>629, 'province_id'=>56, 'name'=>'Huyện Tam Nông'],
            ['id'=>630, 'province_id'=>56, 'name'=>'Huyện Tháp Mười'],
            ['id'=>631, 'province_id'=>56, 'name'=>'Huyện Cao Lãnh'],
            ['id'=>632, 'province_id'=>56, 'name'=>'Huyện Thanh Bình'],
            ['id'=>633, 'province_id'=>56, 'name'=>'Huyện Lấp Vò'],
            ['id'=>634, 'province_id'=>56, 'name'=>'Huyện Lai Vung'],
            ['id'=>635, 'province_id'=>56, 'name'=>'Huyện Châu Thành'],
            ['id'=>636, 'province_id'=>57, 'name'=>'Thành phố Long Xuyên'],
            ['id'=>637, 'province_id'=>57, 'name'=>'Thành phố Châu Đốc'],
            ['id'=>638, 'province_id'=>57, 'name'=>'Huyện An Phú'],
            ['id'=>639, 'province_id'=>57, 'name'=>'Thị xã Tân Châu'],
            ['id'=>640, 'province_id'=>57, 'name'=>'Huyện Phú Tân'],
            ['id'=>641, 'province_id'=>57, 'name'=>'Huyện Châu Phú'],
            ['id'=>642, 'province_id'=>57, 'name'=>'Huyện Tịnh Biên'],
            ['id'=>643, 'province_id'=>57, 'name'=>'Huyện Tri Tôn'],
            ['id'=>644, 'province_id'=>57, 'name'=>'Huyện Châu Thành'],
            ['id'=>645, 'province_id'=>57, 'name'=>'Huyện Chợ Mới'],
            ['id'=>646, 'province_id'=>57, 'name'=>'Huyện Thoại Sơn'],
            ['id'=>647, 'province_id'=>58, 'name'=>'Thành phố Rạch Giá'],
            ['id'=>648, 'province_id'=>58, 'name'=>'Thành phố Hà Tiên'],
            ['id'=>649, 'province_id'=>58, 'name'=>'Huyện Kiên Lương'],
            ['id'=>650, 'province_id'=>58, 'name'=>'Huyện Hòn Đất'],
            ['id'=>651, 'province_id'=>58, 'name'=>'Huyện Tân Hiệp'],
            ['id'=>652, 'province_id'=>58, 'name'=>'Huyện Châu Thành'],
            ['id'=>653, 'province_id'=>58, 'name'=>'Huyện Giồng Riềng'],
            ['id'=>654, 'province_id'=>58, 'name'=>'Huyện Gò Quao'],
            ['id'=>655, 'province_id'=>58, 'name'=>'Huyện An Biên'],
            ['id'=>656, 'province_id'=>58, 'name'=>'Huyện An Minh'],
            ['id'=>657, 'province_id'=>58, 'name'=>'Huyện Vĩnh Thuận'],
            ['id'=>658, 'province_id'=>58, 'name'=>'Thành phố Phú Quốc'],
            ['id'=>659, 'province_id'=>58, 'name'=>'Huyện Kiên Hải'],
            ['id'=>660, 'province_id'=>58, 'name'=>'Huyện U Minh Thượng'],
            ['id'=>661, 'province_id'=>58, 'name'=>'Huyện Giang Thành'],
            ['id'=>662, 'province_id'=>59, 'name'=>'Quận Ninh Kiều'],
            ['id'=>663, 'province_id'=>59, 'name'=>'Quận Ô Môn'],
            ['id'=>664, 'province_id'=>59, 'name'=>'Quận Bình Thuỷ'],
            ['id'=>665, 'province_id'=>59, 'name'=>'Quận Cái Răng'],
            ['id'=>666, 'province_id'=>59, 'name'=>'Quận Thốt Nốt'],
            ['id'=>667, 'province_id'=>59, 'name'=>'Huyện Vĩnh Thạnh'],
            ['id'=>668, 'province_id'=>59, 'name'=>'Huyện Cờ Đỏ'],
            ['id'=>669, 'province_id'=>59, 'name'=>'Huyện Phong Điền'],
            ['id'=>670, 'province_id'=>59, 'name'=>'Huyện Thới Lai'],
            ['id'=>671, 'province_id'=>60, 'name'=>'Thành phố Vị Thanh'],
            ['id'=>672, 'province_id'=>60, 'name'=>'Thành phố Ngã Bảy'],
            ['id'=>673, 'province_id'=>60, 'name'=>'Huyện Châu Thành A'],
            ['id'=>674, 'province_id'=>60, 'name'=>'Huyện Châu Thành'],
            ['id'=>675, 'province_id'=>60, 'name'=>'Huyện Phụng Hiệp'],
            ['id'=>676, 'province_id'=>60, 'name'=>'Huyện Vị Thuỷ'],
            ['id'=>677, 'province_id'=>60, 'name'=>'Huyện Long Mỹ'],
            ['id'=>678, 'province_id'=>60, 'name'=>'Thị xã Long Mỹ'],
            ['id'=>679, 'province_id'=>61, 'name'=>'Thành phố Sóc Trăng'],
            ['id'=>680, 'province_id'=>61, 'name'=>'Huyện Châu Thành'],
            ['id'=>681, 'province_id'=>61, 'name'=>'Huyện Kế Sách'],
            ['id'=>682, 'province_id'=>61, 'name'=>'Huyện Mỹ Tú'],
            ['id'=>683, 'province_id'=>61, 'name'=>'Huyện Cù Lao Dung'],
            ['id'=>684, 'province_id'=>61, 'name'=>'Huyện Long Phú'],
            ['id'=>685, 'province_id'=>61, 'name'=>'Huyện Mỹ Xuyên'],
            ['id'=>686, 'province_id'=>61, 'name'=>'Thị xã Ngã Năm'],
            ['id'=>687, 'province_id'=>61, 'name'=>'Huyện Thạnh Trị'],
            ['id'=>688, 'province_id'=>61, 'name'=>'Thị xã Vĩnh Châu'],
            ['id'=>689, 'province_id'=>61, 'name'=>'Huyện Trần Đề'],
            ['id'=>690, 'province_id'=>62, 'name'=>'Thành phố Bạc Liêu'],
            ['id'=>691, 'province_id'=>62, 'name'=>'Huyện Hồng Dân'],
            ['id'=>692, 'province_id'=>62, 'name'=>'Huyện Phước Long'],
            ['id'=>693, 'province_id'=>62, 'name'=>'Huyện Vĩnh Lợi'],
            ['id'=>694, 'province_id'=>62, 'name'=>'Thị xã Giá Rai'],
            ['id'=>695, 'province_id'=>62, 'name'=>'Huyện Đông Hải'],
            ['id'=>696, 'province_id'=>62, 'name'=>'Huyện Hoà Bình'],
            ['id'=>697, 'province_id'=>63, 'name'=>'Thành phố Cà Mau'],
            ['id'=>698, 'province_id'=>63, 'name'=>'Huyện U Minh'],
            ['id'=>699, 'province_id'=>63, 'name'=>'Huyện Thới Bình'],
            ['id'=>700, 'province_id'=>63, 'name'=>'Huyện Trần Văn Thời'],
            ['id'=>701, 'province_id'=>63, 'name'=>'Huyện Cái Nước'],
            ['id'=>702, 'province_id'=>63, 'name'=>'Huyện Đầm Dơi'],
            ['id'=>703, 'province_id'=>63, 'name'=>'Huyện Năm Căn'],
            ['id'=>704, 'province_id'=>63, 'name'=>'Huyện Phú Tân'],
            ['id'=>705, 'province_id'=>63, 'name'=>'Huyện Ngọc Hiển'],
        ]);
    }
}
